blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/AgenDev-Playground/galactic-ide/discussions
    about: Ask questions and get help from the community in GitHub Discussions.
